args! project.vim
argadd **/*.md
argadd make-docker.*
argadd paper.tex
argadd chicago-author-date.csl
argadd .api_key
argadd .gitignore
argadd Dockerfile
argadd bibliography.bib
argadd references.json
